#!/usr/bin/env python3
"""
Generate 500 first names and 500 last names for the LEOptical Apex seed script.
Draws from multiple locales to reflect a realistic US B2C customer base.

Usage:
    pip install faker
    python3 scripts/generate-name-lists.py

Output: prints two Apex String[] array literals, ready to paste into
        the LEOpticalSeedBatch Apex class.
"""

import random
from faker import Faker

# Target distribution for a US optical retail chain
# (locale, weight) — weights are relative, not percentages
LOCALES = [
    ("en_US",  25),   # Western / generic American
    ("es_MX",  20),   # Hispanic / Latino
    ("zh_CN",  12),   # East Asian — Chinese
    ("ja_JP",   5),   # East Asian — Japanese
    ("ko_KR",   5),   # East Asian — Korean
    ("hi_IN",  12),   # South Asian — Hindi
    ("en_IN",   6),   # South Asian — English India
    ("ar_AA",   5),   # Arab / Middle Eastern
    ("pt_BR",   5),   # Brazilian Portuguese
    ("fr_FR",   5),   # French / West African surnames
]

TARGET = 500

BLOCKLIST = {'Gollum'}

def is_latin(name):
    """Return True if name contains only ASCII letters, spaces, hyphens, and apostrophes."""
    return all(c.isascii() for c in name) and name not in BLOCKLIST

def collect_names(locale, n, seed_offset=0):
    fake = Faker(locale)
    Faker.seed(42 + seed_offset)
    first_names = set()
    last_names = set()
    attempts = 0
    while (len(first_names) < n or len(last_names) < n) and attempts < n * 50:
        fn = fake.first_name()
        ln = fake.last_name()
        if is_latin(fn):
            first_names.add(fn)
        if is_latin(ln):
            last_names.add(ln)
        attempts += 1
    return list(first_names)[:n], list(last_names)[:n]

def main():
    random.seed(42)

    all_first = []
    all_last = []

    total_weight = sum(w for _, w in LOCALES)

    for i, (locale, weight) in enumerate(LOCALES):
        n = round(TARGET * weight / total_weight)
        try:
            first, last = collect_names(locale, n, seed_offset=i * 100)
            all_first.extend(first)
            all_last.extend(last)
        except Exception as e:
            print(f"// Warning: locale {locale} failed: {e}")

    # Deduplicate preserving order, then shuffle
    all_first = list(dict.fromkeys(all_first))
    all_last = list(dict.fromkeys(all_last))

    random.shuffle(all_first)
    random.shuffle(all_last)

    # Backfill to TARGET using en_US if other locales didn't yield enough Latin names
    if len(all_first) < TARGET or len(all_last) < TARGET:
        fake_en = Faker("en_US")
        Faker.seed(999)
        while len(all_first) < TARGET:
            n = fake_en.first_name()
            if is_latin(n) and n not in all_first:
                all_first.append(n)
        while len(all_last) < TARGET:
            n = fake_en.last_name()
            if is_latin(n) and n not in all_last:
                all_last.append(n)

    # Trim to exactly TARGET
    all_first = all_first[:TARGET]
    all_last = all_last[:TARGET]

    # Sanitize: remove single quotes (would break Apex string literals)
    all_first = [n.replace("'", "") for n in all_first]
    all_last = [n.replace("'", "") for n in all_last]

    def to_apex_array(names, var_name):
        quoted = [f"'{n}'" for n in names]
        # 5 names per line for readability
        lines = []
        for i in range(0, len(quoted), 5):
            lines.append("    " + ", ".join(quoted[i:i+5]))
        inner = ",\n".join(lines)
        return f"static final List<String> {var_name} = new List<String>{{\n{inner}\n}};"

    print("// ── Generated by scripts/generate-name-lists.py ──")
    print("// Paste these into LEOpticalSeedBatch.cls\n")
    print(to_apex_array(all_first, "FIRST_NAMES"))
    print()
    print(to_apex_array(all_last, "LAST_NAMES"))
    print(f"\n// First names: {len(all_first)}, Last names: {len(all_last)}")

if __name__ == "__main__":
    main()
